export const aplomoCapabilityStatuses = [
  "complete",
  "partial",
  "missing",
  "planned",
] as const;

export type AplomoCapabilityStatus =
  (typeof aplomoCapabilityStatuses)[number];

export const aplomoCapabilityCriticalities = [
  "core",
  "high",
  "medium",
  "low",
] as const;

export type AplomoCapabilityCriticality =
  (typeof aplomoCapabilityCriticalities)[number];

export const aplomoCapabilityLayers = [
  "domain",
  "contracts",
  "database",
  "rls",
  "repository",
  "service",
  "audit",
  "export",
  "analytics",
  "data_quality",
  "ui",
  "ai_governance",
  "cloud_readiness",
] as const;

export type AplomoCapabilityLayer =
  (typeof aplomoCapabilityLayers)[number];

export type AplomoBackendCapability = {
  id: string;
  name: string;
  description: string;
  criticality: AplomoCapabilityCriticality;
  primaryTables: string[];
  domainFiles: string[];
  contractFiles: string[];
  uiSurfaces: string[];
  requiredPolicies: string[];
  requiredExports: string[];
  requiredAnalytics: string[];
  requiredDataQualityRules: string[];
  cloudTargets: string[];
  layerStatuses: Record<AplomoCapabilityLayer, AplomoCapabilityStatus>;
  gaps: string[];
  nextActions: string[];
};

const createLayerStatuses = (
  overrides: Partial<Record<AplomoCapabilityLayer, AplomoCapabilityStatus>>,
): Record<AplomoCapabilityLayer, AplomoCapabilityStatus> => {
  return Object.fromEntries(
    aplomoCapabilityLayers.map((layer) => [layer, overrides[layer] ?? "missing"]),
  ) as Record<AplomoCapabilityLayer, AplomoCapabilityStatus>;
};

const capability = (input: Omit<AplomoBackendCapability, "layerStatuses"> & {
  layerStatuses: Partial<Record<AplomoCapabilityLayer, AplomoCapabilityStatus>>;
}): AplomoBackendCapability => ({
  ...input,
  layerStatuses: createLayerStatuses(input.layerStatuses),
});

export const aplomoBackendCapabilityRegistry = [
  capability({
    id: "tenant_management",
    name: "Tenant / Company Management",
    description: "Multi-tenant company foundation for SaaS customers, platform visibility and enterprise account management.",
    criticality: "core",
    primaryTables: ["aplomo_companies"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["AplomoSuperAdminPanel", "AplomoSystemSurfaceAuditMatrixPanel"],
    requiredPolicies: ["aplomo_companies_select_platform", "aplomo_companies_select_member"],
    requiredExports: ["tenant_list_csv", "tenant_health_json"],
    requiredAnalytics: ["tenant_count", "active_tenant_count", "tenant_last_activity"],
    requiredDataQualityRules: ["company_slug_required", "company_name_required"],
    cloudTargets: ["aws", "azure", "gcp", "supabase", "vercel"],
    layerStatuses: {
      domain: "partial",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "complete",
      service: "missing",
      audit: "partial",
      export: "partial",
      analytics: "complete",
      data_quality: "missing",
      ui: "complete",
      ai_governance: "complete",
      cloud_readiness: "partial",
    },
    gaps: [
      "No existe todavía servicio server-side de tenant lifecycle.",
      "No existe panel completo de administración de tenants.",
      "No existe data quality runner para companies.",
    ],
    nextActions: [
      "Crear Tenant Management Service.",
      "Crear Tenant Management Panel.",
      "Registrar reglas de calidad para companies.",
    ],
  }),
  capability({
    id: "identity_profiles",
    name: "Identity Profiles",
    description: "User profile foundation mapped to Supabase Auth with platform roles and operational metadata.",
    criticality: "core",
    primaryTables: ["aplomo_profiles"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["AplomoSuperAdminPanel"],
    requiredPolicies: ["aplomo_profiles_select_platform", "aplomo_profiles_select_self", "aplomo_profiles_insert_self", "aplomo_profiles_update_self"],
    requiredExports: ["users_csv"],
    requiredAnalytics: ["profile_count", "platform_role_distribution"],
    requiredDataQualityRules: ["profile_email_present", "platform_role_valid"],
    cloudTargets: ["supabase_auth", "enterprise_sso_future"],
    layerStatuses: {
      domain: "partial",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "complete",
      service: "missing",
      audit: "partial",
      export: "missing",
      analytics: "partial",
      data_quality: "missing",
      ui: "partial",
      ai_governance: "partial",
      cloud_readiness: "planned",
    },
    gaps: [
      "No existe User & Role Admin Panel completo.",
      "No existe servicio server-side de administración de usuarios.",
      "No existe export dedicado de usuarios.",
    ],
    nextActions: [
      "Crear User & Role Admin Panel.",
      "Crear Identity/Profile Service.",
      "Agregar export de perfiles y roles.",
    ],
  }),
  capability({
    id: "tenant_memberships_rbac",
    name: "Tenant Memberships and RBAC",
    description: "Role-based access control per company with tenant role, status, permission overrides and scope.",
    criticality: "core",
    primaryTables: ["aplomo_company_memberships"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["AplomoSuperAdminPanel"],
    requiredPolicies: ["aplomo_memberships_select_platform", "aplomo_memberships_select_member", "aplomo_memberships_insert_manager", "aplomo_memberships_update_manager"],
    requiredExports: ["rbac_matrix_csv"],
    requiredAnalytics: ["active_membership_count", "tenant_admin_count", "role_distribution"],
    requiredDataQualityRules: ["membership_unique_company_profile", "membership_role_valid"],
    cloudTargets: ["enterprise_sso_future", "iam_mapping_future"],
    layerStatuses: {
      domain: "complete",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "complete",
      service: "missing",
      audit: "partial",
      export: "missing",
      analytics: "partial",
      data_quality: "missing",
      ui: "partial",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "No existe matriz visual formal de RBAC.",
      "No existe servicio server-side de asignación de roles.",
      "No existe auditoría fuerte de cambios de permisos.",
    ],
    nextActions: [
      "Crear RBAC Matrix Panel.",
      "Crear RBAC Service.",
      "Auditar cambios de role, status, permissions_override y scope.",
    ],
  }),
  capability({
    id: "site_operations",
    name: "Site Operations",
    description: "Operational sites, yards, plants and physical locations where devices, stockpiles and captures live.",
    criticality: "core",
    primaryTables: ["aplomo_sites"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["AplomoSuperAdminPanel", "Operations surfaces"],
    requiredPolicies: ["aplomo_sites_select_platform", "aplomo_sites_select_member", "aplomo_sites_insert_ops", "aplomo_sites_update_ops"],
    requiredExports: ["sites_csv", "site_operations_json"],
    requiredAnalytics: ["site_count", "devices_by_site", "stockpiles_by_site"],
    requiredDataQualityRules: ["site_name_required", "site_company_required"],
    cloudTargets: ["gis_future", "maps_provider_future"],
    layerStatuses: {
      domain: "partial",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "partial",
      service: "missing",
      audit: "partial",
      export: "missing",
      analytics: "complete",
      data_quality: "missing",
      ui: "partial",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "No existe CRUD completo de sites.",
      "No existe servicio de lifecycle para patios/plantas.",
      "No existe export dedicado de sites.",
    ],
    nextActions: [
      "Crear Site Operations Admin Panel.",
      "Crear Site Operations Service.",
      "Agregar export y KPIs por site.",
    ],
  }),
  capability({
    id: "material_catalog",
    name: "Material Catalog",
    description: "Catalog of material types, codes and densities for engineering calculations and stockpile analytics.",
    criticality: "high",
    primaryTables: ["aplomo_material_types"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: [],
    requiredPolicies: ["aplomo_materials_select_platform", "aplomo_materials_select_member", "aplomo_materials_insert_ops", "aplomo_materials_update_ops"],
    requiredExports: ["materials_csv"],
    requiredAnalytics: ["material_distribution", "density_coverage"],
    requiredDataQualityRules: ["material_name_required", "density_valid_when_present"],
    cloudTargets: ["erp_mapping_future"],
    layerStatuses: {
      domain: "partial",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "partial",
      service: "missing",
      audit: "partial",
      export: "missing",
      analytics: "partial",
      data_quality: "missing",
      ui: "missing",
      ai_governance: "partial",
      cloud_readiness: "planned",
    },
    gaps: [
      "El catálogo de materiales existe en base de datos pero casi no se ve en UI.",
      "No existe CRUD de materiales.",
      "No existen reglas de calidad para densidad.",
    ],
    nextActions: [
      "Crear Material Catalog Panel.",
      "Crear Material Catalog Service.",
      "Agregar reglas de calidad para densidad y códigos.",
    ],
  }),
  capability({
    id: "device_fleet",
    name: "Device Fleet",
    description: "Industrial devices including phones, tablets, gateways, drones, GNSS receivers, RTK base/rover and future hardware.",
    criticality: "core",
    primaryTables: ["aplomo_devices"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["AplomoSuperAdminPanel", "Map panels", "Admin panels"],
    requiredPolicies: ["aplomo_devices_select_platform", "aplomo_devices_select_member", "aplomo_devices_insert_ops", "aplomo_devices_update_ops"],
    requiredExports: ["device_fleet_csv", "device_inventory_json"],
    requiredAnalytics: ["device_count", "device_type_distribution", "online_device_count"],
    requiredDataQualityRules: ["device_name_required", "device_type_valid", "device_company_required"],
    cloudTargets: ["aws_iot_core", "azure_iot_hub", "mqtt", "edge_gateway_future"],
    layerStatuses: {
      domain: "complete",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "complete",
      service: "missing",
      audit: "partial",
      export: "partial",
      analytics: "complete",
      data_quality: "missing",
      ui: "complete",
      ai_governance: "complete",
      cloud_readiness: "partial",
    },
    gaps: [
      "No existe Device Fleet Service server-side.",
      "No existe panel avanzado de administración de flota.",
      "No existen adapters cloud IoT.",
    ],
    nextActions: [
      "Crear Device Fleet Management Panel.",
      "Crear Device Fleet Service.",
      "Crear interfaces de adapters IoT para AWS, Azure y MQTT.",
    ],
  }),
  capability({
    id: "device_sessions",
    name: "Device Sessions",
    description: "Runtime sessions for devices, capture clients, gateways and industrial integrations.",
    criticality: "high",
    primaryTables: ["aplomo_device_sessions"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: [],
    requiredPolicies: ["aplomo_sessions_select_platform", "aplomo_sessions_select_member", "aplomo_sessions_insert_ops", "aplomo_sessions_update_ops"],
    requiredExports: ["device_sessions_csv"],
    requiredAnalytics: ["active_sessions", "session_duration", "session_type_distribution"],
    requiredDataQualityRules: ["session_device_required", "session_started_at_required"],
    cloudTargets: ["iot_runtime", "observability_future"],
    layerStatuses: {
      domain: "partial",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "partial",
      service: "missing",
      audit: "partial",
      export: "missing",
      analytics: "partial",
      data_quality: "missing",
      ui: "missing",
      ai_governance: "partial",
      cloud_readiness: "planned",
    },
    gaps: [
      "No existe timeline visual por sesión.",
      "No existe servicio de lifecycle de sesiones.",
      "No existe export ni analítica profunda de sesiones.",
    ],
    nextActions: [
      "Crear Device Session Timeline.",
      "Crear Device Session Service.",
      "Agregar métricas de duración y estado.",
    ],
  }),
  capability({
    id: "device_connections",
    name: "Device Connections",
    description: "Connection patterns across browser, cellular, WiFi, ethernet, MQTT, NTRIP, MAVLink and future vendor SDKs.",
    criticality: "high",
    primaryTables: ["aplomo_device_connections"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: [],
    requiredPolicies: ["aplomo_connections_select_platform", "aplomo_connections_select_member", "aplomo_connections_insert_ops", "aplomo_connections_update_ops"],
    requiredExports: ["device_connections_csv"],
    requiredAnalytics: ["connection_type_distribution", "active_connection_count"],
    requiredDataQualityRules: ["connection_device_required", "connection_type_or_kind_required"],
    cloudTargets: ["mqtt", "aws_iot", "azure_iot", "edge_gateway_future"],
    layerStatuses: {
      domain: "complete",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "partial",
      service: "missing",
      audit: "partial",
      export: "missing",
      analytics: "partial",
      data_quality: "partial",
      ui: "missing",
      ai_governance: "partial",
      cloud_readiness: "partial",
    },
    gaps: [
      "No existe Connectivity Diagnostics Panel.",
      "No existe servicio de diagnósticos de conexión.",
      "La compatibilidad legacy ya fue reparada pero falta DQ formal.",
    ],
    nextActions: [
      "Crear Connectivity Diagnostics Panel.",
      "Crear Connection Diagnostics Service.",
      "Agregar reglas DQ de conexión.",
    ],
  }),
  capability({
    id: "stockpile_management",
    name: "Stockpile Management",
    description: "Industrial stockpile records with site, material, volume, weight and operational metadata.",
    criticality: "core",
    primaryTables: ["aplomo_stockpiles"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["Stockpile panels", "Super Admin"],
    requiredPolicies: ["aplomo_stockpiles_select_platform", "aplomo_stockpiles_select_member", "aplomo_stockpiles_insert_ops", "aplomo_stockpiles_update_ops"],
    requiredExports: ["stockpiles_csv", "stockpile_inventory_json"],
    requiredAnalytics: ["estimated_volume_total", "estimated_weight_total", "stockpile_count"],
    requiredDataQualityRules: ["stockpile_name_required", "volume_non_negative", "weight_non_negative"],
    cloudTargets: ["warehouse_export", "bi_export"],
    layerStatuses: {
      domain: "complete",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "complete",
      service: "missing",
      audit: "partial",
      export: "partial",
      analytics: "complete",
      data_quality: "missing",
      ui: "complete",
      ai_governance: "complete",
      cloud_readiness: "partial",
    },
    gaps: [
      "CRUD completo de stockpiles todavía es parcial.",
      "No hay servicio server-side de stockpile lifecycle.",
      "No hay data quality runner para volumen/peso.",
    ],
    nextActions: [
      "Crear Stockpile Management + Analytics Panel.",
      "Crear Stockpile Service.",
      "Agregar reglas de calidad de volumen y peso.",
    ],
  }),
  capability({
    id: "gps_capture",
    name: "GPS Capture",
    description: "Manual and device-originated GPS capture events for field operations, evidence and mapping.",
    criticality: "core",
    primaryTables: ["aplomo_gps_captures"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["Capture app", "Map panels"],
    requiredPolicies: ["aplomo_gps_captures_select_platform", "aplomo_gps_captures_select_member", "aplomo_gps_captures_insert_capture"],
    requiredExports: ["gps_captures_csv", "gps_geojson_future"],
    requiredAnalytics: ["capture_count", "average_accuracy", "captures_by_operator"],
    requiredDataQualityRules: ["latitude_range", "longitude_range", "accuracy_non_negative"],
    cloudTargets: ["maps_provider_future", "geospatial_warehouse"],
    layerStatuses: {
      domain: "complete",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "complete",
      service: "missing",
      audit: "partial",
      export: "partial",
      analytics: "complete",
      data_quality: "missing",
      ui: "complete",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "No existe GPS ingestion service server-side.",
      "No existe export GeoJSON.",
      "No existe panel avanzado de desempeño por capturista.",
    ],
    nextActions: [
      "Crear GPS Ingestion Service.",
      "Agregar GPS CSV/GeoJSON exports.",
      "Crear Capture History & Operator Performance Panel.",
    ],
  }),
  capability({
    id: "latest_positions",
    name: "Latest Device Positions",
    description: "Latest known position per device for live map, monitoring, GPS quality and operational awareness.",
    criticality: "core",
    primaryTables: ["aplomo_latest_device_positions"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["Live map", "Super Admin"],
    requiredPolicies: ["aplomo_latest_positions_select_platform", "aplomo_latest_positions_select_member", "aplomo_latest_positions_insert_ops", "aplomo_latest_positions_update_ops"],
    requiredExports: ["latest_positions_csv", "fleet_geojson_future"],
    requiredAnalytics: ["live_position_count", "high_precision_position_count", "accuracy_distribution"],
    requiredDataQualityRules: ["position_device_unique", "latitude_range", "longitude_range"],
    cloudTargets: ["maps", "iot_streaming_future"],
    layerStatuses: {
      domain: "complete",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "complete",
      service: "missing",
      audit: "partial",
      export: "partial",
      analytics: "complete",
      data_quality: "missing",
      ui: "complete",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "No existe servicio server-side de position upsert.",
      "Falta capa visual fuerte de calidad GPS.",
      "No hay streaming adapter.",
    ],
    nextActions: [
      "Crear Position Ingestion Service.",
      "Agregar GPS Quality Overlay.",
      "Preparar adapters IoT/streaming.",
    ],
  }),
  capability({
    id: "operational_alerts",
    name: "Operational Alerts",
    description: "Operational warning and risk signals for devices, GPS quality, sites and stockpile operations.",
    criticality: "high",
    primaryTables: ["aplomo_operational_alerts"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["partial admin surfaces"],
    requiredPolicies: ["aplomo_alerts_select_platform", "aplomo_alerts_select_member", "aplomo_alerts_insert_ops", "aplomo_alerts_update_ops"],
    requiredExports: ["alerts_csv"],
    requiredAnalytics: ["open_alert_count", "alerts_by_severity", "alerts_by_category"],
    requiredDataQualityRules: ["alert_title_required", "severity_valid", "status_valid"],
    cloudTargets: ["notification_provider_future", "observability_future"],
    layerStatuses: {
      domain: "complete",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "partial",
      service: "missing",
      audit: "partial",
      export: "missing",
      analytics: "complete",
      data_quality: "partial",
      ui: "partial",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "No existe Operational Alert Center.",
      "No existe servicio de reglas de alerta conectado a DB.",
      "No existe export de alertas.",
    ],
    nextActions: [
      "Crear Operational Alert Center.",
      "Crear Alert Rule Engine Service.",
      "Agregar export y auditoría de alertas.",
    ],
  }),
  capability({
    id: "data_exports",
    name: "Data Exports",
    description: "Export records and future unified export center for CSV, JSON, Excel, BI and warehouse pipelines.",
    criticality: "high",
    primaryTables: ["aplomo_data_exports"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["health exports", "crosswalk exports"],
    requiredPolicies: ["aplomo_exports_select_platform", "aplomo_exports_select_member", "aplomo_exports_insert_ops", "aplomo_exports_update_ops"],
    requiredExports: ["all_export_types"],
    requiredAnalytics: ["export_count", "exports_by_format", "exports_by_status"],
    requiredDataQualityRules: ["export_format_valid", "export_status_valid"],
    cloudTargets: ["s3", "gcs", "azure_blob", "snowflake", "databricks", "bigquery"],
    layerStatuses: {
      domain: "partial",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "partial",
      service: "missing",
      audit: "partial",
      export: "complete",
      analytics: "partial",
      data_quality: "partial",
      ui: "partial",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "No existe Data Export Center unificado.",
      "No existe servicio de export jobs.",
      "No existen adapters S3/GCS/Azure Blob.",
    ],
    nextActions: [
      "Crear Export Center Service.",
      "Crear Data Export Center.",
      "Crear contratos para warehouse/cloud exports.",
    ],
  }),
  capability({
    id: "audit_logs",
    name: "Audit Logs",
    description: "Cross-system audit trail for sensitive and operational actions.",
    criticality: "core",
    primaryTables: ["aplomo_audit_logs"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: [],
    requiredPolicies: ["aplomo_audit_logs_select_platform", "aplomo_audit_logs_select_member"],
    requiredExports: ["audit_logs_csv"],
    requiredAnalytics: ["audit_event_count", "events_by_type"],
    requiredDataQualityRules: ["audit_action_required", "audit_created_at_required"],
    cloudTargets: ["siem_future", "observability_future"],
    layerStatuses: {
      domain: "partial",
      contracts: "partial",
      database: "complete",
      rls: "complete",
      repository: "partial",
      service: "missing",
      audit: "complete",
      export: "missing",
      analytics: "partial",
      data_quality: "partial",
      ui: "missing",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "No existe Audit Log Viewer.",
      "No existe Audit Service universal usado por todos los writes.",
      "No existe export de audit logs.",
    ],
    nextActions: [
      "Crear Audit Service.",
      "Crear Audit Log Viewer.",
      "Auditar operaciones CRUD críticas.",
    ],
  }),
  capability({
    id: "customer_health",
    name: "Customer Health",
    description: "Internal SaaS customer health scoring, history, trends and exportable customer success signals.",
    criticality: "high",
    primaryTables: ["aplomo_customer_health_snapshots"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["Customer Health Panel", "Health Snapshots", "Health Trends", "Health Export"],
    requiredPolicies: ["aplomo_health_snapshots_select_platform", "aplomo_health_snapshots_insert_platform"],
    requiredExports: ["customer_health_csv", "customer_health_json"],
    requiredAnalytics: ["average_health_score", "risk_customers", "health_delta"],
    requiredDataQualityRules: ["score_range_0_100", "band_valid"],
    cloudTargets: ["crm_future", "warehouse_future"],
    layerStatuses: {
      domain: "complete",
      contracts: "complete",
      database: "complete",
      rls: "complete",
      repository: "complete",
      service: "partial",
      audit: "partial",
      export: "complete",
      analytics: "complete",
      data_quality: "partial",
      ui: "complete",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "Health scoring todavía vive demasiado en frontend.",
      "No hay job programado server-side.",
      "No hay DQ run formal de health snapshots.",
    ],
    nextActions: [
      "Mover scoring a servicio/job server-side.",
      "Auditar snapshot generation.",
      "Agregar DQ rules de health.",
    ],
  }),
  capability({
    id: "support_workflows",
    name: "Platform Support Workflows",
    description: "Internal Aplomo customer success workflows with owners, risk, priority, next touch and notes.",
    criticality: "high",
    primaryTables: ["aplomo_platform_support_workflows"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["Support Workflow Panel", "Support Health Crosswalk"],
    requiredPolicies: ["aplomo_support_workflows_select_platform", "aplomo_support_workflows_insert_platform", "aplomo_support_workflows_update_platform"],
    requiredExports: ["support_workflows_csv", "support_crosswalk_json"],
    requiredAnalytics: ["open_workflows", "urgent_workflows", "blocked_workflows"],
    requiredDataQualityRules: ["workflow_title_required", "priority_valid", "status_valid"],
    cloudTargets: ["crm_future", "ticketing_future"],
    layerStatuses: {
      domain: "complete",
      contracts: "complete",
      database: "complete",
      rls: "complete",
      repository: "complete",
      service: "partial",
      audit: "partial",
      export: "complete",
      analytics: "complete",
      data_quality: "partial",
      ui: "complete",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "Workflow writes todavía están muy cerca del frontend.",
      "No hay timeline histórico de notas.",
      "No hay integración CRM/ticketing.",
    ],
    nextActions: [
      "Crear Support Workflow Service.",
      "Agregar workflow detail drawer y timeline.",
      "Preparar CRM/ticketing adapter.",
    ],
  }),
  capability({
    id: "ai_readiness_packets",
    name: "AI Readiness Packets",
    description: "Governed context packets for future LLMs and agents without exposing secrets or unmanaged data.",
    criticality: "high",
    primaryTables: ["aplomo_ai_readiness_packets"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["Aplomo AI Readiness Panel"],
    requiredPolicies: ["aplomo_ai_packets_select_platform", "aplomo_ai_packets_insert_platform", "aplomo_ai_packets_update_platform"],
    requiredExports: ["ai_packet_json", "ai_prompt_context_txt"],
    requiredAnalytics: ["packet_count", "approved_packet_count", "sensitive_packet_count"],
    requiredDataQualityRules: ["packet_sensitivity_valid", "packet_has_purpose", "packet_has_redaction_notes"],
    cloudTargets: ["openai_future", "anthropic_future", "google_ai_future"],
    layerStatuses: {
      domain: "complete",
      contracts: "complete",
      database: "complete",
      rls: "complete",
      repository: "complete",
      service: "partial",
      audit: "complete",
      export: "complete",
      analytics: "partial",
      data_quality: "partial",
      ui: "complete",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "Packet generation todavía debe moverse a servicio gobernado.",
      "No hay DQ runner de paquetes.",
      "No hay provider gateway todavía, intencionalmente.",
    ],
    nextActions: [
      "Crear AI Readiness Service.",
      "Agregar packet quality checks.",
      "Conectar después al LLM Gateway en modo dry-run.",
    ],
  }),
  capability({
    id: "ai_prompt_registry",
    name: "AI Prompt Registry",
    description: "Versioned registry of prompts with owners, surfaces, sensitivity, model allowlists and approval status.",
    criticality: "high",
    primaryTables: ["aplomo_ai_prompt_registry"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["AI Governance Prompt Registry Panel"],
    requiredPolicies: ["aplomo_ai_prompt_registry_select_platform", "aplomo_ai_prompt_registry_insert_platform", "aplomo_ai_prompt_registry_update_platform"],
    requiredExports: ["prompt_registry_json"],
    requiredAnalytics: ["prompt_count", "approved_prompt_count", "sensitive_prompt_count"],
    requiredDataQualityRules: ["prompt_key_required", "version_unique", "system_prompt_required"],
    cloudTargets: ["llm_gateway_future"],
    layerStatuses: {
      domain: "complete",
      contracts: "complete",
      database: "complete",
      rls: "complete",
      repository: "complete",
      service: "partial",
      audit: "complete",
      export: "missing",
      analytics: "partial",
      data_quality: "partial",
      ui: "complete",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "No hay export completo del prompt registry.",
      "No hay prompt diff/version history visual.",
      "Prompt lifecycle debe moverse a servicio.",
    ],
    nextActions: [
      "Crear Prompt Governance Service.",
      "Agregar prompt version history.",
      "Agregar export JSON del registry.",
    ],
  }),
  capability({
    id: "ai_governance_events",
    name: "AI Governance Events",
    description: "Auditable event stream for prompt, packet and future provider gateway governance actions.",
    criticality: "high",
    primaryTables: ["aplomo_ai_governance_events"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: ["AI Governance Prompt Registry Panel"],
    requiredPolicies: ["aplomo_ai_governance_events_select_platform", "aplomo_ai_governance_events_insert_platform"],
    requiredExports: ["ai_governance_events_csv"],
    requiredAnalytics: ["governance_event_count", "risk_event_count"],
    requiredDataQualityRules: ["event_type_required", "event_summary_required"],
    cloudTargets: ["llm_gateway_future", "audit_export_future"],
    layerStatuses: {
      domain: "complete",
      contracts: "complete",
      database: "complete",
      rls: "complete",
      repository: "complete",
      service: "partial",
      audit: "complete",
      export: "missing",
      analytics: "complete",
      data_quality: "partial",
      ui: "complete",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "No hay export de eventos de gobernanza.",
      "No hay timeline visual avanzado.",
      "El futuro gateway debe escribir aquí obligatoriamente.",
    ],
    nextActions: [
      "Crear AI Governance Timeline.",
      "Agregar governance events export.",
      "Hacer obligatorio el registro de eventos desde LLM Gateway.",
    ],
  }),
  capability({
    id: "schema_migration_ledger",
    name: "Schema Migration Ledger",
    description: "Canonical ledger for expected migrations, applied migrations, schema audit findings and capability status.",
    criticality: "core",
    primaryTables: ["planned: aplomo_schema_migration_ledger", "planned: aplomo_schema_audit_findings", "planned: aplomo_schema_capability_status"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: [],
    requiredPolicies: ["planned_schema_platform_policies"],
    requiredExports: ["schema_audit_csv"],
    requiredAnalytics: ["missing_migrations", "schema_drift_count"],
    requiredDataQualityRules: ["migration_id_unique", "capability_status_valid"],
    cloudTargets: ["ci_cd", "supabase", "future_managed_postgres"],
    layerStatuses: {
      domain: "planned",
      contracts: "planned",
      database: "missing",
      rls: "planned",
      repository: "missing",
      service: "missing",
      audit: "planned",
      export: "missing",
      analytics: "planned",
      data_quality: "planned",
      ui: "missing",
      ai_governance: "complete",
      cloud_readiness: "partial",
    },
    gaps: [
      "No existe ledger real de migraciones.",
      "No existe auditoría persistida de schema drift.",
      "No hay UI de schema health.",
    ],
    nextActions: [
      "Crear migración de schema ledger.",
      "Crear schema audit repository.",
      "Crear Schema Health Panel.",
    ],
  }),
  capability({
    id: "data_quality_lineage",
    name: "Data Quality and Lineage Core",
    description: "Data assets, data quality rules, quality runs and lineage edges for BI, warehouse and AI trust.",
    criticality: "core",
    primaryTables: ["planned: aplomo_data_assets", "planned: aplomo_data_quality_rules", "planned: aplomo_data_quality_runs", "planned: aplomo_data_lineage_edges"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: [],
    requiredPolicies: ["planned_data_quality_platform_policies"],
    requiredExports: ["data_quality_report_csv", "lineage_json"],
    requiredAnalytics: ["quality_score", "failed_rule_count", "asset_coverage"],
    requiredDataQualityRules: ["quality_rule_valid", "lineage_edge_valid"],
    cloudTargets: ["snowflake", "databricks", "bigquery", "redshift", "powerbi"],
    layerStatuses: {
      domain: "planned",
      contracts: "planned",
      database: "missing",
      rls: "planned",
      repository: "missing",
      service: "missing",
      audit: "planned",
      export: "planned",
      analytics: "planned",
      data_quality: "planned",
      ui: "missing",
      ai_governance: "complete",
      cloud_readiness: "partial",
    },
    gaps: [
      "No existen data assets, quality rules, quality runs ni lineage edges.",
      "No hay Data Quality Center.",
      "No hay readiness formal para Snowflake/Databricks/Power BI.",
    ],
    nextActions: [
      "Crear Data Quality + Lineage Core migration.",
      "Crear DQ repository y rule runner.",
      "Crear Data Quality Center.",
    ],
  }),
  capability({
    id: "cloud_integration_readiness",
    name: "Cloud Integration Readiness",
    description: "Neutral cloud connector architecture for AWS, Azure, Google Cloud, Supabase, Vercel, BI and warehouse systems.",
    criticality: "high",
    primaryTables: ["planned: aplomo_cloud_connectors", "planned: aplomo_external_system_mappings", "planned: aplomo_integration_runs", "planned: aplomo_integration_events"],
    domainFiles: ["packages/domain/src/aplomoPlatformCapabilityRegistry.ts"],
    contractFiles: ["packages/api-contracts/src/aplomoPlatformCapabilityContracts.ts"],
    uiSurfaces: [],
    requiredPolicies: ["planned_cloud_connector_policies"],
    requiredExports: ["integration_runs_csv"],
    requiredAnalytics: ["integration_success_rate", "integration_failure_count"],
    requiredDataQualityRules: ["connector_type_valid", "external_mapping_valid"],
    cloudTargets: ["aws", "azure", "gcp", "supabase", "vercel", "snowflake", "databricks"],
    layerStatuses: {
      domain: "planned",
      contracts: "planned",
      database: "missing",
      rls: "planned",
      repository: "missing",
      service: "missing",
      audit: "planned",
      export: "planned",
      analytics: "planned",
      data_quality: "planned",
      ui: "missing",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "No existen cloud connectors.",
      "No existen integration runs/events.",
      "No existe Integration Center.",
    ],
    nextActions: [
      "Crear Cloud Integration Readiness migration.",
      "Crear provider-neutral connector contracts.",
      "Crear Integration Center.",
    ],
  }),
  capability({
    id: "llm_provider_gateway",
    name: "LLM Provider Gateway",
    description: "Future server-side gateway for OpenAI, Anthropic, Google and other providers with allowlists, dry-run mode, audit and governance.",
    criticality: "high",
    primaryTables: ["planned: aplomo_llm_provider_requests", "planned: aplomo_llm_provider_responses"],
    domainFiles: ["planned"],
    contractFiles: ["planned"],
    uiSurfaces: [],
    requiredPolicies: ["planned_llm_gateway_policies"],
    requiredExports: ["llm_audit_json"],
    requiredAnalytics: ["llm_request_count", "llm_dry_run_count", "llm_blocked_request_count"],
    requiredDataQualityRules: ["approved_prompt_required", "approved_packet_required", "sensitivity_allowed"],
    cloudTargets: ["openai", "anthropic", "google_ai", "azure_openai", "aws_bedrock"],
    layerStatuses: {
      domain: "planned",
      contracts: "planned",
      database: "missing",
      rls: "planned",
      repository: "missing",
      service: "missing",
      audit: "planned",
      export: "planned",
      analytics: "planned",
      data_quality: "planned",
      ui: "missing",
      ai_governance: "complete",
      cloud_readiness: "planned",
    },
    gaps: [
      "Gateway intencionalmente pausado hasta completar backend/data/governance.",
      "No existen tablas de request/response.",
      "No existe servicio server-side de provider calls.",
    ],
    nextActions: [
      "Completar schema ledger y data quality primero.",
      "Crear gateway en dry-run antes de llamadas reales.",
      "Exigir prompt y packet aprobados para toda llamada real.",
    ],
  }),
] as const satisfies readonly AplomoBackendCapability[];

export const getAplomoBackendCapabilityById = (
  id: string,
): AplomoBackendCapability | undefined => {
  return aplomoBackendCapabilityRegistry.find((capability) => capability.id === id);
};

export const getAplomoBackendCapabilitiesByCriticality = (
  criticality: AplomoCapabilityCriticality,
): AplomoBackendCapability[] => {
  return aplomoBackendCapabilityRegistry.filter(
    (capability) => capability.criticality === criticality,
  );
};

export const getAplomoBackendCapabilitiesByLayerStatus = (
  layer: AplomoCapabilityLayer,
  status: AplomoCapabilityStatus,
): AplomoBackendCapability[] => {
  return aplomoBackendCapabilityRegistry.filter(
    (capability) => capability.layerStatuses[layer] === status,
  );
};

export const flattenAplomoBackendCapabilityLayers = () => {
  return aplomoBackendCapabilityRegistry.flatMap((capability) =>
    aplomoCapabilityLayers.map((layer) => ({
      capabilityId: capability.id,
      capabilityName: capability.name,
      criticality: capability.criticality,
      layer,
      status: capability.layerStatuses[layer],
    })),
  );
};

export const summarizeAplomoBackendCapabilityRegistry = () => {
  const flattened = flattenAplomoBackendCapabilityLayers();

  return {
    capabilityCount: aplomoBackendCapabilityRegistry.length,
    layerCount: flattened.length,
    completeLayerCount: flattened.filter((item) => item.status === "complete").length,
    partialLayerCount: flattened.filter((item) => item.status === "partial").length,
    missingLayerCount: flattened.filter((item) => item.status === "missing").length,
    plannedLayerCount: flattened.filter((item) => item.status === "planned").length,
    coreCapabilityCount: aplomoBackendCapabilityRegistry.filter(
      (capability) => capability.criticality === "core",
    ).length,
    cloudTargetCount: new Set(
      aplomoBackendCapabilityRegistry.flatMap((capability) => capability.cloudTargets),
    ).size,
  };
};
